name: Projections

on:
  push:
    branches:
      - master

jobs:
  holobranch-projections:
    runs-on: ubuntu-latest
    steps:
    - name: 'Update holobranch: emergence/layer/master'
      uses: JarvusInnovations/hologit@actions/projector/v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        HAB_LICENSE: accept
      with:
        holobranch: emergence-layer
        commit-to: emergence/layer/master
