name: 'Release: Projections'

on:
  push:
    tags: [ 'v*' ]

env:
  GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
  HAB_LICENSE: accept

jobs:
  release-projections:
    runs-on: ubuntu-latest
    steps:

    - name: 'Update holobranch: emergence/layer/master'
      uses: JarvusInnovations/hologit@actions/projector/v1
      with:
        holobranch: emergence-layer
        commit-to: emergence/layer/master
